from __future__ import annotations

from typing import Protocol
from uuid import UUID

from .domain import Belief, Edge, Evidence, Node, RewireEvent
from .events import BrainEvent


class EventStore(Protocol):
    def append(self, event: BrainEvent) -> None: ...


class BeliefRepository(Protocol):
    def get(self, belief_id: UUID) -> Belief | None: ...
    def save(self, belief: Belief) -> None: ...


class EvidenceRepository(Protocol):
    def save(self, evidence: Evidence) -> None: ...
    def get(self, evidence_id: UUID) -> Evidence | None: ...


class GraphRepository(Protocol):
    def upsert_node(self, node: Node) -> None: ...
    def upsert_edge(self, edge: Edge) -> None: ...
    def get_edge(self, edge_id: UUID) -> Edge | None: ...
    def log_rewire(self, event: RewireEvent) -> None: ...
